// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TesteStarWars.Starwarsapi_Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ApiStarWars")]
    public partial class ApiStarWarsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ApiStarWars.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ApiStarWars", "Criando testes de api StarWars", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01_Case test StarWars ApiPeople")]
        [NUnit.Framework.CategoryAttribute("Cenario")]
        [NUnit.Framework.CategoryAttribute("People")]
        [NUnit.Framework.CategoryAttribute("deve")]
        [NUnit.Framework.CategoryAttribute("retornar")]
        [NUnit.Framework.CategoryAttribute("Luke")]
        [NUnit.Framework.CategoryAttribute("Skywalker")]
        public virtual void _01_CaseTestStarWarsApiPeople()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01_Case test StarWars ApiPeople", null, new string[] {
                        "Cenario",
                        "People",
                        "deve",
                        "retornar",
                        "Luke",
                        "Skywalker"});
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
testRunner.When("passo o id da pessoa \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
testRunner.Then("recebo o nome da pessoa \'Luke Skywalker\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02_Case test StarWars ApiPeoples")]
        [NUnit.Framework.CategoryAttribute("Cenario")]
        [NUnit.Framework.CategoryAttribute("People")]
        [NUnit.Framework.CategoryAttribute("deve")]
        [NUnit.Framework.CategoryAttribute("retornar")]
        [NUnit.Framework.CategoryAttribute("C-3PO")]
        public virtual void _02_CaseTestStarWarsApiPeoples()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02_Case test StarWars ApiPeoples", null, new string[] {
                        "Cenario",
                        "People",
                        "deve",
                        "retornar",
                        "C-3PO"});
#line 10
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 11
testRunner.When("passo o id da pessoa \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
testRunner.Then("recebo o nome da pessoa \'C-3PO\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03_Case test StarWars ApiPlanets")]
        [NUnit.Framework.CategoryAttribute("Cenario")]
        [NUnit.Framework.CategoryAttribute("Planets")]
        [NUnit.Framework.CategoryAttribute("deve")]
        [NUnit.Framework.CategoryAttribute("retornar")]
        [NUnit.Framework.CategoryAttribute("Tatooine")]
        public virtual void _03_CaseTestStarWarsApiPlanets()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03_Case test StarWars ApiPlanets", null, new string[] {
                        "Cenario",
                        "Planets",
                        "deve",
                        "retornar",
                        "Tatooine"});
#line 15
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 16
testRunner.When("passo o id do planeta \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
testRunner.Then("recebo o nome do planeta \'Tatooine\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04_Case test StarWars ApiPlanets")]
        [NUnit.Framework.CategoryAttribute("Cenario")]
        [NUnit.Framework.CategoryAttribute("Planets")]
        [NUnit.Framework.CategoryAttribute("deve")]
        [NUnit.Framework.CategoryAttribute("retornar")]
        [NUnit.Framework.CategoryAttribute("Alderaan")]
        public virtual void _04_CaseTestStarWarsApiPlanets()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04_Case test StarWars ApiPlanets", null, new string[] {
                        "Cenario",
                        "Planets",
                        "deve",
                        "retornar",
                        "Alderaan"});
#line 20
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 21
testRunner.When("passo o id do planeta \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
testRunner.Then("recebo o nome do planeta \'Alderaan\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05_Case test StarWars ApiSpecies")]
        [NUnit.Framework.CategoryAttribute("Cenario")]
        [NUnit.Framework.CategoryAttribute("Species")]
        [NUnit.Framework.CategoryAttribute("deve")]
        [NUnit.Framework.CategoryAttribute("retornar")]
        [NUnit.Framework.CategoryAttribute("Human")]
        public virtual void _05_CaseTestStarWarsApiSpecies()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05_Case test StarWars ApiSpecies", null, new string[] {
                        "Cenario",
                        "Species",
                        "deve",
                        "retornar",
                        "Human"});
#line 25
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 26
testRunner.When("passo o id da especie \'1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
testRunner.Then("recebo o nome da especie \'Human\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06_Case test StarWars ApiSpecies")]
        [NUnit.Framework.CategoryAttribute("Cenario")]
        [NUnit.Framework.CategoryAttribute("Species")]
        [NUnit.Framework.CategoryAttribute("deve")]
        [NUnit.Framework.CategoryAttribute("retornar")]
        [NUnit.Framework.CategoryAttribute("Droid")]
        public virtual void _06_CaseTestStarWarsApiSpecies()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06_Case test StarWars ApiSpecies", null, new string[] {
                        "Cenario",
                        "Species",
                        "deve",
                        "retornar",
                        "Droid"});
#line 30
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 31
testRunner.When("passo o id da especie \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
testRunner.Then("recebo o nome da especie \'Droid\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07_Case test StarWars ApiStarships")]
        [NUnit.Framework.CategoryAttribute("Cenario")]
        [NUnit.Framework.CategoryAttribute("Starships")]
        [NUnit.Framework.CategoryAttribute("deve")]
        [NUnit.Framework.CategoryAttribute("retornar")]
        [NUnit.Framework.CategoryAttribute("CR90")]
        [NUnit.Framework.CategoryAttribute("corvette")]
        public virtual void _07_CaseTestStarWarsApiStarships()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07_Case test StarWars ApiStarships", null, new string[] {
                        "Cenario",
                        "Starships",
                        "deve",
                        "retornar",
                        "CR90",
                        "corvette"});
#line 35
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 36
testRunner.When("passo o id do starships \'2\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
testRunner.Then("recebo o nome do starships \'CR90 corvette\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08_Case test StarWars ApiStarships")]
        [NUnit.Framework.CategoryAttribute("Cenario")]
        [NUnit.Framework.CategoryAttribute("Starships")]
        [NUnit.Framework.CategoryAttribute("deve")]
        [NUnit.Framework.CategoryAttribute("retornar")]
        [NUnit.Framework.CategoryAttribute("Star")]
        [NUnit.Framework.CategoryAttribute("Destroyer")]
        public virtual void _08_CaseTestStarWarsApiStarships()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08_Case test StarWars ApiStarships", null, new string[] {
                        "Cenario",
                        "Starships",
                        "deve",
                        "retornar",
                        "Star",
                        "Destroyer"});
#line 40
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 41
testRunner.When("passo o id do starships \'3\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
testRunner.Then("recebo o nome do starships \'Star Destroyer\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
